on:
  push:
    branches:
      - main
jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix-environments: ${{ steps.environment-folders.outputs.matrix }}
    steps:
      - name: Generate matrix
        id: environment-folders
        uses: hellofresh/action-changed-files@v3
        with:
          pattern: (?P<environment>[^/]+)/versions

  deploy:
    needs: [ generate-matrix ]
    concurrency: production
    environment: ${{matrix.environment}}
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix-environments) }}
    if: ${{ fromJson(needs.generate-matrix.outputs.matrix-environments).include[0] }} # skip if the matrix is empty!
    steps:
      - name: Frontend Zip Name
        id: frontendZip
        run: echo "name::frontend-build-$(date +'%Y-%m-%d-%s').zip" >> $GITHUB_OUTPUT
      - name: Repo Checkout
        uses: actions/checkout@v4
      - name: Install sshpass
        run: sudo apt install sshpass
      - name: Configure SSH
        id: ssh
        run: |
          mkdir -p ~/.ssh/
          cat >>~/.ssh/config <<END
          Host prod
            HostName $SSH_HOST
            User $SSH_USER
          END
          ssh-keyscan -H "$SSH_HOST" > ~/.ssh/known_hosts
        env:
          SSH_USER: ${{ vars.SSH_USER_NAME }}
          SSH_HOST: ${{ vars.SSH_HOST }}
      - name: Check for Error Marker
        env:
          SSHPASS: ${{ secrets.SSH_USER_PASSWORD }}
        run:
          sshpass -e ssh prod "test ! -f deploy-error"
      - name: Load versions
        uses: aarcangeli/load-dotenv@v1.0.0
        with:
          path: ${{matrix.environment}}
          filenames: versions
          if-file-not-found: error
      - name: clone backend # only used to check if the given ref exists.
        uses: actions/checkout@v4.1.1
        with:
          repository: ${{ env.BACKEND_REPO }}
          ref: ${{ env.BACKEND_HASH}}
          path: 'backend'
      - name: clone frontend
        uses: actions/checkout@v4.1.1
        with:
          repository: ${{ env.FRONTEND_REPO }}
          ref: ${{ env.FRONTEND_HASH}}
          path: 'frontend'
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with:
          node-version: 16
      - name: build frontend
        working-directory: frontend
        env:
          REACT_APP_CLIENT_ID: ${{ secrets.FRONTEND_CLIENT_ID}}
          REACT_APP_CLIENT_SECRET: '${{ secrets.FRONTEND_CLIENT_SECRET }}'
          REACT_APP_API: '${{ vars.BACKEND_URL }}'
        run: |
          npm install
          npm run build
          cd build
          zip -r build *
      - name: Copy Frontend to Server
        env:
          SSHPASS: ${{ secrets.SSH_USER_PASSWORD }}
          BACKUPS: ${{ vars.BACKUP_PATH}}
          FRONTEND_NAME: ${{ steps.frontendZip.outputs.name }}
        run: |
          sshpass -e scp frontend/build/build.zip prod:$BACKUPS/$FRONTEND_NAME
      - name: Update backend
        env:
          SSHPASS: ${{ secrets.SSH_USER_PASSWORD }}
          PUBLIC_HTML: ${{ vars.PUBLIC_HTML_PATH }}
        run:
          sshpass -e ssh prod "cd $PUBLIC_HTML && git fetch && git checkout $BACKEND_HASH && php artisan migrate --force && php artisan optimize"

      - name: Install frontend
        env:
          SSHPASS: ${{ secrets.SSH_USER_PASSWORD }}
          PUBLIC_HTML: ${{ vars.PUBLIC_HTML_PATH }}
          BACKUPS: ${{ vars.BACKUP_PATH}}
          FRONTEND_NAME: ${{ steps.frontendZip.outputs.name }}
        run:
          sshpass -e ssh prod "python3 $PUBLIC_HTML/frontend_patcher.py -s $BACKUPS/$FRONTEND_NAME -t $PUBLIC_HTML"
      - name: Cache views
        env:
          SSHPASS: ${{ secrets.SSH_USER_PASSWORD }}
          PUBLIC_HTML: ${{ vars.PUBLIC_HTML_PATH }}
        run:
          sshpass -e ssh prod "cd $PUBLIC_HTML && php artisan view:cache"
      - name: Create Error Marker
        if: failure() && steps.ssh.outcome == 'success'
        env:
          SSHPASS: ${{ secrets.SSH_USER_PASSWORD }}
        run:
          sshpass -e ssh prod "touch deploy-error"


